# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cosyvoice_pb2 as cosyvoice__pb2


class CosyVoiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_stream(
                '/cosyvoice.CosyVoice/Inference',
                request_serializer=cosyvoice__pb2.Request.SerializeToString,
                response_deserializer=cosyvoice__pb2.Response.FromString,
                )


class CosyVoiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosyVoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_stream_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=cosyvoice__pb2.Request.FromString,
                    response_serializer=cosyvoice__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosyvoice.CosyVoice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CosyVoice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cosyvoice.CosyVoice/Inference',
            cosyvoice__pb2.Request.SerializeToString,
            cosyvoice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
